name: Coverity Actions
run-name: ${{ github.actor }} is running Coverity.
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'main'
      - 'stable-**'
      - '**-stable'
  pull_request:
    branches:
      - 'main'
      - 'stable-**'
      - '**-stable'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows to call this workflow from other workflows
  workflow_call:
jobs:
  Run-Coverity-Analysis:
    runs-on:
      self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: intel-innersource/frameworks.actions.setup-coverity@v1
      with:
        version: 2022.3.1
    - uses: intel-innersource/frameworks.actions.coverity-analysis@v3
      with:
        source: pysvtools
        html-dir: html_report
        fail-if-issues-found: true
